# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kdesu': '@latest-kf6'
    'plasma/plasma-activities': '@latest-kf6'
