/* config-apps.h.  Generated by cmake from config-apps.h.cmake  */

/* Define if you have long long as datatype */
#cmakedefine HAVE_LONG_LONG 1

/* Define to 1 if you have the KActivities library. */
#cmakedefine KActivities_FOUND 1

/* Define where your java executable is */
#undef PATH_JAVA

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* type to use in place of socklen_t if not defined */
#define kde_socklen_t socklen_t
