/* config-apps.h.  Generated by cmake from config-apps.h.cmake  */

/* Define to 1 if you have the KActivities library. */
#cmakedefine KActivities_FOUND 1

/* Define where your java executable is */
#undef PATH_JAVA

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64
