/* config-konqueror.h.  Generated by cmake from config-konqueror.h.cmake  */

/* Define to 1 if you have the KActivities library. */
#cmakedefine KActivities_FOUND 1

/* Define to 1 to enable developer mode */
#cmakedefine DEVELOPER_MODE
