# SPDX-FileCopyrightText: 2024-2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: konqueror
confinement: strict
grade: stable
base: core24
adopt-info: konqueror
apps:
  konqueror:
    extensions:
      - kde-neon-6
    common-id: org.kde.konqueror.desktop
    desktop: usr/share/applications/konqbrowser.desktop
    command: usr/bin/konqueror
    plugs:
      - pulseaudio
      - browser-support
    environment:
      DICPATH: "$SNAP/usr/share/hunspell"
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      QTWEBENGINE_DISABLE_SANDBOX: 1
      XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
      XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
plugs:
  hunspell-dictionaries:
    content: hunspell-dictionaries
    interface: content
    target: "$SNAP/usr/share/hunspell"
    default-provider: hunspell-dictionaries
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.konqueror
    bus: session
parts:
  qca:
    source: https://invent.kde.org/libraries/qca.git
    source-branch: master
    source-depth: 1
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - ca-certificates
      - gnupg
      - libsasl2-dev
      - libssl-dev
      - pkg-config
      - rsync
      - libproxy1v5
    stage-packages:
      - rsync
      - libpopt0
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    override-stage: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  konqueror:
    after:
      - qca
    parse-info:
      - usr/share/metainfo/org.kde.konqueror.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - libxml2-dev
      - gettext
      - doxygen
      - graphviz
      - libxml2-utils
      - docbook-xml
      - docbook-xsl
      - libxcb-util-dev
      - libssl-dev
      - libcups2-dev
      - libxkbcommon-dev
      - libpulse0
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
      - hunspell-dictionaries
    stage-packages:
      - libxcb-util1
      - cups-client
      - libpulse0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
    build-environment:
      - DICPATH: "$CRAFT_STAGE/usr/share/hunspell"
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [konqueror]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - konqueror
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
