[Profile]
Container0_Children=View1,View2
Container0_Orientation=Horizontal
Container0_SplitterSizes=24,100
Height=578
Height 1200=745
Name=File Management
Name[af]=Lêer Bestuurder
Name[ar]=إدارة الملفات
Name[as]=নথিপত্ৰৰ পৰিচালনা
Name[ast]=Xestión de ficheros
Name[be]=Кіраванне файламі
Name[be@latin]=Kiravańnie fajłami
Name[bg]=File Management
Name[bn]=ফাইল ব্যবস্থাপনা
Name[bn_IN]=ফাইল পরিচালনা
Name[br]=Mererezh ar restroù
Name[ca]=Gestió de fitxers
Name[ca@valencia]=Gestió de fitxers
Name[cs]=Správa souborů
Name[csb]=Sprôwianié lopkama
Name[cy]=Trefnu Ffeiliau
Name[da]=Filhåndtering
Name[de]=Dateiverwaltung
Name[el]=Διαχείριση αρχείων
Name[en_GB]=File Management
Name[eo]=Dosieradministrilo
Name[es]=Gestión de archivos
Name[et]=Failihaldur
Name[eu]=Fitxategi-kudeaketa
Name[fa]=مدیریت پرونده‌
Name[fi]=Tiedostonhallinta
Name[fr]=Gestion de fichiers
Name[fy]=Triembehear
Name[ga]=Bainisteoireacht Comhad
Name[gl]=Xestión de ficheiros
Name[gu]=ફાઇલ વ્યવસ્થાપક
Name[he]=מנהל קבצים
Name[hi]=फ़ाइल प्रबंधन
Name[hne]=फाइल प्रबंधन
Name[hr]=Upravitelj datoteka
Name[hsb]=Datajowy manager
Name[hu]=Fájlkezelő
Name[ia]=Gestion de file
Name[id]=Manajemen Berkas
Name[is]=Skráastjóri
Name[it]=Gestione dei file
Name[ja]=ファイルマネージャ
Name[ka]=ფაილთა მართვა
Name[kk]=Файлдарды басқару
Name[km]=ការ​គ្រប់គ្រង​ឯកសារ
Name[kn]=ಕಡತ ವ್ಯವಸ್ಥಾಪನೆ
Name[ko]=파일 관리자
Name[ku]=Rêveberiya Pelan
Name[lt]=Failų valdymas
Name[lv]=Failu pārvaldnieks
Name[mai]=फाइल प्रबंधन
Name[mk]=Менаџмент на датотеки
Name[ml]=ഫയല്‍ നടത്തിപ്പ്
Name[mr]=फाइल व्यवस्थापन
Name[ms]=Pengurusan Fail
Name[nb]=Filbehandling
Name[nds]=Dateipleeg
Name[ne]=फाइल व्यवस्थापन
Name[nl]=Bestandsbeheer
Name[nn]=Filhandsaming
Name[oc]=Gestion de fichièrs
Name[or]=ଫାଇଲ ପରିଚାଳନା
Name[pa]=ਫਾਇਲ ਮੈਨਿਜਮੈਂਟ
Name[pl]=Zarządzanie plikami
Name[pt]=Gestão de Ficheiros
Name[pt_BR]=Gerenciamento de arquivos
Name[ro]=Administrare fișiere
Name[ru]=Управление файлами
Name[se]=Fiilagieđaheapmi
Name[si]=ගොණු කළමනාකරණය
Name[sk]=Správca súborov
Name[sl]=Upravljanje datotek
Name[sr]=Управљање фајловима
Name[sr@ijekavian]=Управљање фајловима
Name[sr@ijekavianlatin]=Upravljanje fajlovima
Name[sr@latin]=Upravljanje fajlovima
Name[sv]=Filhantering
Name[ta]=கோப்பு மேலாண்மை
Name[te]=దస్త్ర నిర్వహణ
Name[tg]=Идоракунии файлҳо
Name[th]=การจัดการแฟ้ม
Name[tr]=Dosya Yönetimi
Name[ug]=ھۆججەت باشقۇرۇش
Name[uk]=Керування файлами
Name[uz]=Fayl boshqaruvi
Name[uz@cyrillic]=Файл бошқаруви
Name[vi]=Quản lý Tập tin
Name[wa]=Manaedjî les fitchîs
Name[xh]=Uphatho Lwefayile
Name[x-test]=xxFile Managementxx
Name[zh_CN]=文件管理
Name[zh_TW]=檔案管理
RootItem=Container0
View1_LinkedView=true
View1_LockedLocation=false
View1_PassiveMode=true
View1_ServiceName=konq_sidebartng
View1_ServiceType=Browser/View
View1_ToggleView=true
View1_URL=
View2_LinkedView=true
View2_LockedLocation=false
View2_PassiveMode=false
View2_ServiceName=konq_iconview
View2_ServiceType=inode/directory
View2_ToggleView=false
View2_URL=file:///tmp
